version: '3'

services:
  server:
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - database
      - redis

  database:
    image: mongo
    volumes:
      - ./data/db:/data/db
    restart: always

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - server

  redis:
    image: redis
    restart: always
